name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68580e84b91e8935d8ed58b1e7427cc642e580a20f360b10ba2b0e1c7bced697"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
