name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdee0273bec0284fc8db584992c5a4db310242f877f7c50a5afba9f705becbee"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
