name = "GregTech Lite"
author = "Magic_Sweepy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaff416bc16a8a831d8b9383d2163e1f4f3cbf2eb59b8def86280c864f7ccc77"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
